### ISSUE TITLE
Is dkcmd win scratch pop not working?

### ISSUE THREAD

**Issue by TAforever** [natemaia/dk#15]
Maybe I'm doing something wrong, I've never used a scratchpad before but I don't think the command works

https://github.com/user-attachments/assets/e3ac7bc2-7d72-4369-ba49-e23502de03c2

**Comment by natemaia** [comment]
No you're absolutely correct and pop was broken if a window wasn't passed. I just pushed the fix, thanks for the help!

**Comment by TAforever** [comment]
Just tested it and now if you send multiple windows to scratchpad, the window manager crashes on scratch pop command
UPD:  with one window also crashes, but not always

**Comment by natemaia** [comment]
Try the latest

**Comment by TAforever** [comment]
Still crashes, but I forgot to mention that if you enter commands in the terminal, it doesn't crash, but if you use a hotkey, it does crash.
Here's the debug log 
[dk.log](https://github.com/user-attachments/files/17176670/dk.log)
